# Generated by Django 3.2 on 2025-12-01 02:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foodcourtapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='register',
            name='confirm_password',
        ),
    ]
