# Generated by Django 5.2.8 on 2025-12-14 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcourtapp', '0002_remove_register_confirm_password'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=100)),
                ('palace', models.CharField(max_length=100)),
                ('event_type', models.CharField(choices=[('Small Event', 'Small Event'), ('Medium Event', 'Medium Event'), ('Large Event', 'Large Event')], max_length=50)),
                ('number_of_palace', models.PositiveIntegerField()),
                ('food_type', models.CharField(choices=[('Vegetarian', 'Vegetarian'), ('Non-Vegetarian', 'Non-Vegetarian')], max_length=50)),
                ('contact_number', models.CharField(max_length=15)),
                ('email', models.EmailField(max_length=254)),
                ('event_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
