# Generated by Django 5.2.8 on 2025-12-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcourtapp', '0003_booking'),
    ]

    operations = [
        migrations.CreateModel(
            name='StarterFood',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='starter_foods/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
