# Generated by Django 5.2.8 on 2025-12-29 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('foodcourtapp', '0005_drink'),
    ]

    operations = [
        migrations.CreateModel(
            name='Maincourse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='maincourses/')),
            ],
        ),
        migrations.CreateModel(
            name='Offers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='offers/')),
            ],
        ),
        migrations.CreateModel(
            name='Ourspecial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('details', models.TextField(blank=True)),
                ('image', models.ImageField(upload_to='ourspecials/')),
            ],
        ),
    ]
